const form = document.forms.mainForm;
const name = document.getElementById('name');
const email = document.getElementById('email');
const age = document.getElementById('age');
const gender = document.querySelectorAll('input[name="gender"]');
const profession = document.getElementById('profession');
const password = document.getElementById('password');
const passwordRepeat = document.getElementById('password__repeat');
const agreement = document.getElementById('agreement');